server:
  port: 9090
spring:
  application:
    name: "employee-service"
  profiles:
    active: "dev"
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: chuman
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:9071/"

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9060/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"