services:
  employeedb:
    container_name: employeedb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: employeedb
    extends:
      file: common-config.yml
      service: microservice-db-config

  swipindb:
    container_name: swipindb
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: swipindb
    extends:
      file: common-config.yml
      service: microservice-db-config

  swipout:
    container_name: swipout
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: swipout
    extends:
      file: common-config.yml
      service: microservice-db-config

  configserver:
    image: "empsystem/configserver:s7"
    container_name: configserver-ms
    ports:
      - "9071:9071"
    healthcheck:
      test: "curl --fail --silent localhost:9071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: microservice-base-config

  employee:
    image: "empsystem/employeeservice:s7"
    container_name: employee-ms
    ports:
      - "9090:9090"
    environment:
      SPRING_APPLICATION_NAME: "employee-service"
      SPRING_DATASOURCE_URL: "jdbc:mysql://employeedb:3306/employeedb"
    depends_on:
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  swipeinservice:
    image: "empsystem/swipeinservice:s7"
    container_name: swipin-ms
    ports:
      - "9095:9095"
    environment:
      SPRING_APPLICATION_NAME: "swipeinservice"
      SPRING_DATASOURCE_URL: "jdbc:mysql://swipindb:3306/swipindb"
    depends_on:
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

  swipeoutservice:
    image: "empsystem/swipeoutservice:s7"
    container_name: swipeoutservice-ms
    ports:
      - "9045:9045"
    environment:
      SPRING_APPLICATION_NAME: "swipeoutservice"
      SPRING_DATASOURCE_URL: "jdbc:mysql://swipout:3306/swipout"
    depends_on:
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: microservice-configserver-config

networks:
  eazybank:
    driver: "empsystem"